onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild

overrides:
  glob@>=10.2.0 <10.5.0: '>=10.5.0'
  happy-dom@<20.0.0: '>=20.0.0'
  qs@<6.14.1: '>=6.14.1'
  storybook@>=9.0.0 <9.1.17: '>=9.1.17'
